name: flutter_badge_manager_example
description: Demonstrates how to use the flutter_badge_manager plugin.
version: 0.0.1


environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_badge_manager:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true