name: flutter_badge_manager
description: Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
version: 0.0.1-pre.0.1

homepage: https://github.com/ziqq/flutter_badge_manager

repository: https://github.com/ziqq/flutter_badge_manager

issue_tracker: https://github.com/ziqq/flutter_badge_manager/issues

funding:
  - https://www.buymeacoffee.com/ziqq
  - https://www.patreon.com/ziqq
  - https://boosty.to/ziqq

platforms:
  android:
  macos:
  ios:

#screenshots:
#  - description: 'Example of using the library to check app version.'
#    path: example.png


environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  # Integration tests for Flutter
  integration_test:
    sdk: flutter
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.flutterbadgemanager
        pluginClass: FlutterBadgetManagerPlugin
      ios:
        pluginClass: FlutterBadgetManagerPlugin
      macos:
        pluginClass: FlutterBadgetManagerPlugin
