// Copyright 2025 Anton Ustinoff<a.a.ustinoff@gmail.com>.
// Use of this source code is governed by an MIT license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class FlutterBadgeManagerPluginPigeonCodecReader: FlutterStandardReader {
}

private class FlutterBadgeManagerPluginPigeonCodecWriter: FlutterStandardWriter {
}

private class FlutterBadgeManagerPluginPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterBadgeManagerPluginPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterBadgeManagerPluginPigeonCodecWriter(data: data)
  }
}

class FlutterBadgeManagerPluginPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterBadgeManagerPluginPigeonCodec(readerWriter: FlutterBadgeManagerPluginPigeonCodecReaderWriter())
}

/// Package-local Pigeon schema for the iOS and macOS implementation.
///
/// This contract intentionally lives in the foundation package because it
/// generates Swift bindings and foundation-specific channel names.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterBadgeManagerApi {
  /// Returns whether the current platform supports badge updates.
  func isSupported() throws -> Bool?
  /// Applies the given badge count.
  func update(count: Int64) throws
  /// Clears the current badge.
  func remove() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterBadgeManagerApiSetup {
  static var codec: FlutterStandardMessageCodec { FlutterBadgeManagerPluginPigeonCodec.shared }
  /// Sets up an instance of `FlutterBadgeManagerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterBadgeManagerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns whether the current platform supports badge updates.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_badge_manager_foundation.FlutterBadgeManagerApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// Applies the given badge count.
    let updateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_badge_manager_foundation.FlutterBadgeManagerApi.update\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        do {
          try api.update(count: countArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateChannel.setMessageHandler(nil)
    }
    /// Clears the current badge.
    let removeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_badge_manager_foundation.FlutterBadgeManagerApi.remove\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeChannel.setMessageHandler { _, reply in
        do {
          try api.remove()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeChannel.setMessageHandler(nil)
    }
  }
}
